name: local_music
description: "Local Music App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  flutter_remixicon:
    git: https://github.com/KarimAbdo/flutter_remixicon.git
  ionicons: ^0.2.2
  material_design_icons_flutter: ^7.0.7296

  # database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  device_info: ^2.0.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  screenshot: ^2.1.0

  flare_flutter: ^3.0.2
  flare_loading: ^3.0.0
  nb_utils: ^6.0.6

  # state manager
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/res/

  fonts:
    - family: NightMachine
      fonts:
        - asset: assets/fonts/night_machine/NightMachine-Regular.otf
          weight: 400

    - family: Urban
      fonts:
        - asset: assets/fonts/urban/Urbanist-Regular.otf
          weight: 400
        - asset: assets/fonts/urban/Urbanist-Light.otf
          weight: 300
        - asset: assets/fonts/urban/Urbanist-SemiBold.otf
          weight: 600
        - asset: assets/fonts/urban/Urbanist-Bold.otf
          weight: 700

    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.otf
          weight: 400
        - asset: assets/fonts/raleway/Raleway-Thin.otf
          weight: 100
        - asset: assets/fonts/raleway/Raleway-SemiBold.otf
          weight: 600

    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
          weight: 400

    - family: Futura
      fonts:
        - asset: assets/fonts/futura/FuturaLT.ttf
          weight: 400